config/routes.rb
Rails.application.routes.draw do
  

 
  devise_for :users
  

  resources :pages do 
  	resources :comments
  end

  resources :photos do 
  	resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to=> "pages#new"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true    
end

app/models/page.rb
class Page < ApplicationRecord
	has_many :comments, as: :commentable
end

app/models/photo.rb
class Photo < ApplicationRecord
	has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
  protect_from_forgery with: :exception

  def load_commentable
    resource, id = request.path.split('/')[1,2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_commentable

  def index
  	@comments = @commentable.comments

  end

  def show
  end

  def edit
  end

  def new
  	@comment = @commentable.comments.new
  end
  def create
  	@comment = @commentable.comments.new(comment_params)
  	if @comment.save
  		redirect_to @commentable
  	else
  		render 'new'
  	end
  end

  private

  def comment_params
  	params.require(:comment).permit(:content, :comment_type, :commentable_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :load_commentable, only: [:show]


  def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end
  def create
    @page = Page.new(page_params)
    if @page.save
      redirect_to pages_path
    else
      render 'new'
    end
  end

  def edit
    @page = Page.find(params[:id])

  end
  def update
    @page = Page.find(params[:id])
    if @page.update(page_params)
      redirect_to pages_path
    else
      render 'edit'
    end
  end

  def show
    @page = Page.find(params[:id])
    @commentable = @page
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    redirect_to pages_path
    
  end
  def page_params
    params.require(:page).permit(:topic, :description)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :load_commentable, only: [:show]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @comments = @photo.comments
    @comment = Comment.new
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/comments/_comment.html.erb
<% @comments.each do |f| %>
  <%= f.content %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for ([@commentable, @comment]) do |f| %>
   <%= f.label :content %>
   <%= f.text_area :content %>
   
   <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1> Comments </h1>

<%= render 'comment' %>
<br>

<%= link_to 'New Comment', [:new, @commentable, :comment] %>

app/views/comments/new.html.erb
<h1>Comments#news</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
    <%= yield %>
  </body>
</html>

app/views/pages/destroy.html.erb
<h1>Pages#destroy</h1>
<p>Find me in app/views/pages/destroy.html.erb</p>

app/views/pages/edit.html.erb
<%= form_for @page do |p| %>
  <%= p.label :topic %>
  <%= p.text_field :topic %>
  <br><br>
  <%= p.label :description %>
  <%= p.text_area :description %>
  <br><br>
  <%= p.submit 'update' %>
<% end %>

app/views/pages/index.html.erb
<body>
<% @pages.each do |p| %>
<h3><%= p.topic %></h3>
<p><%= p.description %></p>
<%= link_to 'show', page_path(p) %>
<%= link_to 'edit', edit_page_path(p) %>
<%= link_to 'delete',p, :method=> :delete %>
<hr>
<% end %>
<%= link_to 'new', new_page_path %>
</body>

app/views/pages/new.html.erb
<%= form_for @page do |p| %>
  <%= p.label :topic %>
  <%= p.text_field :topic %>
  <br><br>
  <%= p.label :description %>
  <%= p.text_area :description %>
  <br><br>
  <%= p.submit 'save' %>
<% end %>

app/views/pages/show.html.erb
<body>
<h2><%= @page.topic %></h2>
<p><%= @page.description %></p><br><br>

<%= render 'comments/comment' %>
<%= render 'comments/form' %>
</body>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :photo_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.name %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @photo.name %>
</p>
 
 <%= render 'comments/comment' %>
 <%= render 'comments/form' %>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>